### ISSUE TITLE
Support all OpenSSH public keys

### ISSUE THREAD

**Issue by oleks** [DIKUNIX/jordemoder#1]
For instance, the world is [moving on from RSA](https://blog.g3rt.nl/upgrade-your-ssh-keys.html).

**Comment by oleks** [comment]
The key format is part of [RFC 4253, Section 6.6.  Public Key Algorithms](https://tools.ietf.org/html/rfc4253#section-6.6).

**Comment by oleks** [comment]
The easy solution is to use the [sshpubkeys](https://pypi.python.org/pypi/sshpubkeys/1.0.5) Python package.

**Comment by athas** [comment]
Fixed in 482a0ce.
